version: 2
defaults: &defaults
  working_directory: /go/src/istio.io/istio
  docker:
    - image: istio/ci:go1.9-k8s1.7.4
  environment:
    GOPATH: /go

# org context settings. If developing on a clone, please configure:

# DOCKER_USER
# DOCKER_PASS
# HUB: ex istio, costinm (it is not the hub, but the dockerhub org or user)

integrationDefaults: &integrationDefaults
  machine: true
  working_directory: /go/src/istio.io/istio #same as docker
  environment:
    CHANGE_MINIKUBE_NONE_USER: true
    HUB: docker.io/dnerepo
    TAG: dontpush
    GOPATH: /go

jobs:
  e2e-simple:
    <<: *integrationDefaults
    environment:
            - KUBECONFIG: /go/out/minikube.conf
            - TEST_ENV: minikube-none
            - GOPATH: /go
    steps:
      - type: shell
        name: Initialize Working Directory
        pwd: /
        command: |
          sudo mkdir -p /go/src/istio.io/istio
          sudo chown -R circleci /go
          mkdir -p /go/out
          mkdir /home/circleci/logs
      - checkout
      - attach_workspace:
          at:  /go
      - run: bin/testEnvRootMinikube.sh start
      - run: make docker.prebuilt
      - run: bin/testEnvRootMinikube.sh wait
      - run: docker images
      - run: PATH=$GOPATH/bin:$PATH make e2e_simple E2E_ARGS="--skip_delete -use_local_cluster -cluster_wide -alsologtostderr -test.v -v 2 --istioctl ${GOPATH}/bin/istioctl"
      - store_artifacts:
          path: /home/circleci/logs
      - store_artifacts:
          path: /tmp

  e2e-mixer:
    <<: *integrationDefaults
    environment:
            - KUBECONFIG: /go/out/minikube.conf
            - TEST_ENV: minikube-none
            - GOPATH: /go
    steps:
      - type: shell
        name: Initialize Working Directory
        pwd: /
        command: |
          sudo mkdir -p /go/src/istio.io/istio
          sudo chown -R circleci /go
          mkdir -p /go/out
          mkdir /home/circleci/logs
      - checkout
      - attach_workspace:
          at:  /go
      - run: bin/testEnvRootMinikube.sh start
      - run: make docker.prebuilt
      - run: bin/testEnvRootMinikube.sh wait
      - run: docker images
      - run:
            no_output_timeout: 20m
            # Run the test even if previous failed
            when: always
            command: |
                  make e2e_mixer E2E_ARGS="--skip_delete -use_local_cluster -cluster_wide -alsologtostderr -test.v -v 2 --istioctl ${GOPATH}/bin/istioctl"
      - store_artifacts:
          path: /home/circleci/logs
      - store_artifacts:
          path: /tmp

  e2e-bookinfo:
    <<: *integrationDefaults
    environment:
            - KUBECONFIG: /go/out/minikube.conf
            - TEST_ENV: minikube-none
            - GOPATH: /go
    steps:
      - type: shell
        name: Initialize Working Directory
        pwd: /
        command: |
          sudo mkdir -p /go/src/istio.io/istio
          sudo chown -R circleci /go
      - checkout
      - attach_workspace:
          at:  /go
      - run: bin/testEnvRootMinikube.sh start
      - run: make docker.prebuilt
      - run: bin/testEnvRootMinikube.sh wait
      - run: docker images
      - run:
            no_output_timeout: 20m
            when: always
            command: |
              make e2e_bookinfo E2E_ARGS="--skip_delete -use_local_cluster -cluster_wide -alsologtostderr -test.v -v 2 --istioctl ${GOPATH}/bin/istioctl"
      - store_artifacts:
          path: /home/circleci/logs
      - store_artifacts:
          path: /tmp

  e2e-pilot:
    <<: *integrationDefaults
    environment:
            - GOPATH: /go
            - KUBECONFIG: /go/out/minikube.conf
            - TEST_ENV: minikube-none
            - HUB: docker.io/dnerepo
            - TAG: dontpush
    steps:
      - type: shell
        name: Initialize Working Directory
        pwd: /
        command: |
          sudo mkdir -p /go/src/istio.io/istio
          sudo chown -R circleci /go
      - checkout
      - attach_workspace:
          at:  /go
      - run: bin/testEnvRootMinikube.sh start
      - run: make docker.prebuilt
      - run: bin/testEnvRootMinikube.sh wait
      - run: docker images
      - run: $GOPATH/bin/pilot-integration-test --logtostderr -hub $HUB -tag $TAG -mixer=true -auth=enable -errorlogsdir=/home/circleci/logs -use-initializer
      - store_artifacts:
          path: /home/circleci/logs

  e2e-pilot-noauth:
    <<: *integrationDefaults
    environment:
            - GOPATH: /go
            - KUBECONFIG: /go/out/minikube.conf
            - TEST_ENV: minikube-none
            - HUB: docker.io/dnerepo
            - TAG: dontpush
    steps:
      - type: shell
        name: Initialize Working Directory
        pwd: /
        command: |
          sudo mkdir -p /go/src/istio.io/istio
          sudo chown -R circleci /go
      - checkout
      - attach_workspace:
          at:  /go
      - run: bin/testEnvRootMinikube.sh start
      - run: make docker.prebuilt
      - run: bin/testEnvRootMinikube.sh wait
      - run: docker images
      - run: $GOPATH/bin/pilot-integration-test --logtostderr -hub $HUB -tag $TAG -mixer=true -auth=disable -errorlogsdir=/home/circleci/logs -use-initializer
      - store_artifacts:
          path: /home/circleci/logs

  codecov:
    <<: *defaults
    resource_class: xlarge
    environment:
      KUBECONFIG: /go/src/istio.io/istio/.circleci/config
    steps:
      - checkout
      - run: mkdir -p /tmp/coverage
      - run:
          name: Running Kubernetes API Server standalone
          command: /tmp/apiserver/start-test-server.sh
          background: true
      - run:
          command: |
            cd /go/src/istio.io/istio
            make init
      - run: cd /go/src/istio.io/istio; maxprocs=6 bin/parallel-codecov.sh pilot
      - run:
          command: |
            bash <(curl -s https://codecov.io/bash) -F pilot
      - run: cd /go/src/istio.io/istio; maxprocs=6 bin/parallel-codecov.sh security/pkg
      - run: cd /go/src/istio.io/istio; maxprocs=6 bin/parallel-codecov.sh security/cmd
      - run:
          command: |
            bash <(curl -s https://codecov.io/bash) -F security
      - run: cd /go/src/istio.io/istio; maxprocs=6 bin/parallel-codecov.sh broker
      - run:
          command: |
            bash <(curl -s https://codecov.io/bash) -F broker
      - run: cd /go/src/istio.io/istio; maxprocs=6 bin/parallel-codecov.sh mixer
      - run:
          command: |
            bash <(curl -s https://codecov.io/bash) -F mixer

  test:
    <<: *defaults
    environment:
      KUBECONFIG: /go/src/istio.io/istio/.circleci/config
    resource_class: xlarge
    steps:
      - checkout
      - run:
          command: |
            mkdir -p /go/out/tests
            go get github.com/jstemmer/go-junit-report
            free
            trap "go-junit-report </go/out/tests/go-test-report.out > /go/out/tests/go-test-report.xml" EXIT
            make localTestEnv
            make pilot-test mixer-test broker-test security-test T=-v | tee -a /go/out/tests/go-test-report.out
      - store_test_results:
          path: /go/out/tests

  racetest:
    <<: *defaults
    environment:
      KUBECONFIG: /go/src/istio.io/istio/.circleci/config
    resource_class: xlarge
    steps:
      - checkout
      - run:
          command: |
            mkdir -p /go/out/racetests
            go get github.com/jstemmer/go-junit-report
            free
            trap "go-junit-report </go/out/racetests/go-racetest-report.out > /go/out/racetests/go-racetest-report.xml" EXIT
            make localTestEnv
            make -k pilot-racetest mixer-racetest broker-racetest security-racetest T=-v | tee -a /go/out/racetests/go-racetest-report.out
      - store_test_results:
          path: /go/out/racetests

  build:
    <<: *defaults
    resource_class: xlarge
    steps:
      - checkout
      - run:
          command: |
            cd /go/src/istio.io/istio
            make init go-build test-bins
      - persist_to_workspace:
          root: /go
          paths:
            # pkg may include 'dep'
            - pkg/linux_amd64
            - bin
      - run:  make sidecar.deb
      - store_artifacts:
          path: /go/out/istio-sidecar.deb

  lint:
    <<: *defaults
    environment:
      KUBECONFIG: /go/src/istio.io/istio/.circleci/config
    resource_class: xlarge
    steps:
      - checkout
      - run: make lint

  ## TODO DISBALE ME and use the container based lint
  # lint:
  #   <<: *integrationDefaults
  #   steps:
  #     - type: shell
  #       name: Initialize Working Directory
  #       pwd: /
  #       command: |
  #         sudo mkdir -p /go/src/istio.io/istio
  #         sudo chown -R circleci /go
  #     - checkout
  #     - run:
  #         no_output_timeout: 15m
  #         command: |
  #           make lint

  docker-push:
    <<: *defaults
    resource_class: xlarge
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            if [ ! -z "${DOCKER_USER}" ] ; then
              echo "Pushing docker images"
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
              make docker push
            fi

  goxbuild:
    <<: *defaults
    resource_class: xlarge
    steps:
      - checkout
      - run:
          command: |
            cp -a /usr/local/go /go
            export PATH=/go/go/bin:$PATH
            export GOROOT=/go/go
            cd /go/src/istio.io/istio
            make go-build GOOS=darwin KUBECONFIG=/go/src/istio.io/istio/.circleci/config
            make go-build GOOS=linux GOARCH=arm KUBECONFIG=/go/src/istio.io/istio/.circleci/config
      - store_artifacts:
          path: /go/bin

workflows:
  version: 2
  nightly:
    triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
    jobs: #daisy chained steps ending with docker push
      - build
      - test:
          requires:
            - build
      - e2e-simple:
          requires:
            - test
      - e2e-bookinfo:
          requires:
            - test
      - e2e-mixer:
          requires:
            - test
      - e2e-pilot:
          requires:
            - test
      - e2e-pilot-noauth:
          requires:
            - test
      # Compile for mac and arm
      - goxbuild:
          requires:
            - test
      # Push to dockerhub
      - docker-push:
          context: org-global
          requires:
            - e2e-bookinfo
            - e2e-mixer
            - e2e-pilot
            - e2e-pilot-noauth

  periodic:
    triggers:
       - schedule:
           cron: "20 1,4,7,10,13,16,19,22 * * *"
           filters:
             branches:
               only:
                 - master
    jobs:
      - build
      - codecov:
          requires:
            - build
      - test
      - racetest
      - e2e-simple:
          requires:
            - build
      - e2e-bookinfo:
          requires:
            - build
      - e2e-mixer:
          requires:
            - build
      - e2e-pilot:
          requires:
            - build
      - e2e-pilot-noauth:
          requires:
            - build

  all:
    jobs:
      - lint
      - build
      - test
      - e2e-pilot:
          requires:
            - build
